#!/usr/bin/env escript
%% -*- erlang -*- 

main([Src, Dest]) ->
  PostgresUrl = "DATABASE_URL",
  MongoHQUrl = "MONGOHQ_URL",
  {HttpPort, _} = string:to_integer(os:getenv("PORT")),

  % transform file into a dictionary
  {ok, [Terms]} = file:consult(Src),
  TermsDic = dict:from_list(Terms),
  {ok, BossTerms} = dict:find(boss, TermsDic),
  SrcBossConfig = dict:from_list(BossTerms),

  % database connection setup
  {EnvVar, DatabaseType} = case dict:find(db_adapter, SrcBossConfig) of
    {ok, mongodb} -> io:format("MongoDb configuration detected.~n"), {MongoHQUrl, mongodb};
    {ok, pgsql} -> io:format("Postgres database configuration detected.~n"), {PostgresUrl, pgsql};
    {_, Type} -> io:format("database type '~p' for key 'db_adapter' is unsupported. Postgres and MongoDb are supported.~n", [Type]), erlang:error(bad_db_type)
  end,

  % database connection string parsing
  io:format("parsing envar~n"),
  Url = os:getenv(EnvVar),
  {ok, {dbType, UserPass, Host, DbPort, [$/ | DbName], _}} = http_uri:parse(Url),
  [Username, Password] = string:tokens(UserPass, ":"),
  HerokuSettings = [{port, HttpPort},{db_host, Host}, 
                    {db_port, DbPort}, {db_username, Username},
                    {db_password, Password}, {db_database, DbName},
                    {db_adapter, DatabaseType}],
  BossConfigured = lists:foldl(fun({K, V}, Acc)->
    dict:store(K, V, Acc)
  end, SrcBossConfig, HerokuSettings),
  CombinedConfig = dict:store(boss, dict:to_list(BossConfigured), SrcBossConfig),

  %lager params
  BossConfigOutput = dict:store(lager, [{handlers,
    [{lager_console_backend, info}]},
    {crash_log, "priv/sasl/crash.log"}], CombinedConfig),

  {ok, S} = file:open(Dest, write),
  io:format(S, "~p.", [dict:to_list(BossConfigOutput)]),
  {ok, [AppName|_]} = dict:find(applications, SrcBossConfig),
  io:format("~s's boss.config transformation finished.~n", [AppName]);

main(_) ->
  io:format("usage: cb_config <src_config_file> <destination_config_file>~n").

